[package]
name = "civ_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.10.2"
ic-cdk-macros = "0.7.0"
candid = { version = "0.9.11", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

aes-gcm = { version = "0.10", default-features = false, features = ["aes", "alloc"] }
base64 = "0.21"
getrandom = { version = "0.2.16", features = ["js"] }
zeroize = { version = "1.7", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
